# -*- coding: utf-8 -*-
"""category 3 problem1 boolean hooligans

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-2q4yrOGMQNaK8UeU9-5qqg3F4ej_PMw
"""

T = int(input())
count=0
if T < 1 or T > 1000:
  print("invalid input")

while count <=T:
  if T < 1 or T > 1000:
    break
  count = count + 1
  x = int(input())
  if x < 1 or x > 1000:
    print("invalid input")
  i = 0
  if x<=10:
    print(x)
  else:
    print(x % 10)